### ISSUE TITLE
No usb-devices and hid-keyboard

### ISSUE THREAD

**Issue by Duvio** [urbanadventurer/Android-PIN-Bruteforce#10]
I suspect that this is because i am not on Kali NetHunter, where can i get those binaries from ?

Galaxy S10 (SM-G973F)
Android 10

**Comment by 0x300T** [comment]
[binary.zip](https://github.com/urbanadventurer/Android-PIN-Bruteforce/files/5986240/binary.zip)
Download the binary zip and extract.
but you need to modify the script to use without kali nethunter

**Comment by urbanadventurer** [comment]
I'm interested to learn if this works out of the box or if you need to do anything else first.

**Comment by Duvio** [comment]
@urbanadventurer 
I didnt try it out yet, but ill do when i can (today - UTC)

**Comment by 0x300T** [comment]
> I'm interested to learn if this works out of the box or if you need to do anything else first.

it will surely work without nethunter 
but need to modify your script a little bit

i will update you once done editing the script and tried

**Comment by urbanadventurer** [comment]
If you just want `/system/xbin/hid-keyboard`, that's a compiled version of `hid_gadget_test.c`. This is a small program for testing the HID gadget driver that is included in the Linux Kernel. The source code for this file can be found at https://www.kernel.org/doc/html/latest/usb/gadget_hid.html.

@0x300T provided compiled versions, but if you want to compile your own you can do this.

This worked on my phone, but it might not work on yours:
copy/paste the source code into a file named `hid-keyboard.c` then execute the following commands:

```
make hid-keyboard
cp hid-keyboard /usr/local/bin/
chmod +x /usr/local/bin/hid-keyboard
/usr/local/bin/hid-keyboard
```

In your case you can then update the `config` file with the new location for the hid-keyboard executable.

```
# Operating System Environment
KEYBOARD_DEVICE=/dev/hidg0
HID_KEYBOARD=/system/xbin/hid-keyboard
```

You can download the `usb-devices` script from https://github.com/gregkh/usbutils/blob/master/usb-devices

By the way, I've just updated the script so that it doesn't require `usb-devices` to work.

**Comment by 0x300T** [comment]
@urbanadventurer  hid-keyboard from that zip is generic. should also work for him.

**Comment by 0x300T** [comment]
@urbanadventurer it worked out of the box without kali nethunter.only in su terminal.just had to ported bash in /system/bin/ folder.
![Screenshot_2021-02-18-11-21-45-809_com offsec nhterm](https://user-images.githubusercontent.com/78304032/108309494-cca3de80-71db-11eb-9225-3aed85dfe308.jpg)

**Comment by Duvio** [comment]
Cannot confirm
There was no `hid` file in `/dev/` for me

**Comment by 0x300T** [comment]
> Cannot confirm
> There was no `hid` file in `/dev/` for me

kernel support hid?? and did yoy enable hid??

**Comment by urbanadventurer** [comment]
Have a look at this https://github.com/pelya/android-keyboard-gadget/blob/master/README.md

I'll close this issue now.
