### ISSUE TITLE
Google Pixel 2 XL, Restart slight workaround

### ISSUE THREAD

**Issue by cherno-bill-ampill** [urbanadventurer/Android-PIN-Bruteforce#15]
Android 10 I think. I've been fiddling with a 2xl manually, it increases the cooldown by 30 seconds for about each 25 tries. So after a 100 tries the cooldown is 120 seconds. It remembers the number of tries after a restart but the cooldown will be 0 seconds. Restarting takes 20-30 seconds and ~1% battery charge.

I don't have a nethunter set up yet, should I even bother? Can it restart through OTG? Is it going to take too long anyway? It may even burn the charge too fast but as long as it's automated I may okay with that. Btw there are no other real ways to approach this besides bruteforcing, right?

**Comment by urbanadventurer** [comment]
if you are a technical user, you can get this working without NetHunter on an Android phone with an appropriate Linux kernel. You will need to source or compile some the binaries yourself. A non-NetHunter approach is not officially supported because a lot of non-technical users will ask for help. It's going to be easier for everyone at this stage of development if they use NetHunter.

I have been unable to cause a phone to reboot through any key combinations sent via an OTG cable. Please let me know if you find a way to do this.

Brute-forcing is the simplest approach. Some companies have products that use other approaches and that is discussed in the README file.

Will you be releasing your config file with the timings you figured out?

**Comment by urbanadventurer** [comment]
I'm closing this issue now. Please let me know if you successfully made a config file for the  Google Pixel 2 XL.
